answer_1 = "init"
answer_2 = "int"
answer_3 = "while"
answer_4 = "IaaS provides virtualized computing resources over the internet (like AWS EC2 or Google Compute Engine), PaaS offers hardware and software tools over the internet (like like AWS RDS for PostgreSQL, MySQL), and SaaS delivers software over the internet (like Youtube, Office 365)."
answer_5 = "Pros: Scalability, Cost-efficiency, Enhanced security (up-to-date systems, advanced security), High availability, Global access. Cons: Security concerns (data control), Dependence on internet, Expensive one time purchase."
answer_6 = "Benefits include scalability, flexibility, and ability to deploy and update small software packages independently."
answer_7 = "OnPrem services are utilized when there is a need for greater control over security, particularly in case of highly sensitive data."